server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: ${ISSUER_ENDPOINT:http://localhost:9000}
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASSWORD:root}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/user-db?authSource=admin
