server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: ${ISSUER_ENDPOINT:http://localhost:9000}
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASSWORD:root}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/user-db?authSource=admin

oauth2:
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}

mongock:
  change-logs-scan-package:
    - com.innowise.songmanager.authapi.repository.migration