server:
  port: 0

spring:
  application:
    name: song-api
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
      region:
        static: ${AWS_REGION:eu-west-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:root}
        secret-key: ${AWS_SECRET_KEY:root}
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASSWORD:root}@localhost:27018/song-metadata-db?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

file-api:
  url: http://localhost:8080