version: '3.1'

services:
  mongo:
    image: mongo:6.0.6
    container_name: auth-api-mongo
    restart: always
    ports:
      - '27019:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/var/lib/mongodb/data

volumes:
  mongo-data:
