server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_ENDPOINT:http://localhost:8761/eureka}

logging:
  level:
    com.netflix.eureka: off
    com.netflix.discovery: off