server:
  port: 0

spring:
  application:
    name: file-api
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
      region:
        static: ${AWS_REGION:eu-west-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:root}
        secret-key: ${AWS_SECRET_KEY:root}
      s3:
        path-style-access-enabled: on
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGODB_USER:root}
      password: ${MONGODB_PASSWORD:root}
      database: ${MONGODB_DATABASE:song-db}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

file-api:
  storage:
    local-path: uploads/
    bucket-name: songs
