server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: ${PROFILE:native}
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
        git:
          uri: ${GIT_URI}
          clone-on-start: true
